- name: test playbook
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!!"
    - name: install http
      yum:
        - name: htghy
          state: present
          
